### ISSUE TITLE
Cannot be built in release mode on my setup

### ISSUE THREAD

**Issue by Dadoum** [ChristopherHX/libjnivm#7]
```
undefined reference to int jnivm::defaultVal<int>(jnivm::ENV*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)
```

and stack of other derrivatives of template.

(it can be built but not linked with anything, and this is the error)

**Comment by ChristopherHX** [comment]
Please try the clang-8-fix branch: https://github.com/ChristopherHX/libjnivm/tree/clang-8-fix. I think this fixes your build / link error.

(It would be helpful if you provide information about your compiler name and version)

**Comment by Dadoum** [comment]
gcc/g++ 10.2.0 and thanks it works
